### ISSUE TITLE
Karma-nodeunit test suite does not pass in Chrome

### ISSUE THREAD

**Issue by alexstrat** [karma-runner/karma-nodeunit#9]
I'm trying to debug a bug – `setUp` `tearDown` does not work – in karma-nodeunit (or maybe a the version of nodeunit itself), but the karma-nodeunint test suite does even not pass in Chrome:

``` sh
$ grunt test
Running "karma:adapter" (karma) task
INFO [karma]: Karma v0.10.4 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 32.0.1700 (Mac OS X 10.8.5)]: Connected on socket r7wszDpnxsBx_rOFTu3a
..
Chrome 32.0.1700 (Mac OS X 10.8.5) nodeunit adapter  running a suite of tests should report test failures FAILED
    Error: Uncaught Error: expected 'equal\nAssertionError\n    at Object.equal (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1526:39)\n    at fixtureSuite.failing.This is only a test (/Users/alex/Code/karma-nodeunit/test/test-fixture.js:11:12)\n    at Object.exports.runTest (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1702:9)\n    at /Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1748:25\n    at /Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1006:13\n    at iterate (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:616:13)\n    at async.forEachSeries (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:632:9)\n    at _concat (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1005:9)\n    at Object.concatSeries (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:645:23)\n    at Object.exports.runSuite (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1727:11)' to contain 'AssertionError: "real" == "this"' (/Users/alex/Code/karma-nodeunit/node_modules/sinon/pkg/sinon.js:1399)
        at global.onerror (/Users/alex/Code/karma-nodeunit/node_modules/mocha/mocha.js:5469:10)
Chrome 32.0.1700 (Mac OS X 10.8.5) nodeunit adapter  running a suite of tests should report test failures FAILED
    Error: Uncaught Error: expected 'equal\nAssertionError\n    at Object.equal (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1526:39)\n    at fixtureSuite.failing.This is only a test (/Users/alex/Code/karma-nodeunit/test/test-fixture.js:11:12)\n    at Object.exports.runTest (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1702:9)\n    at /Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1748:25\n    at /Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1006:13\n    at iterate (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:616:13)\n    at async.forEachSeries (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:632:9)\n    at _concat (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1005:9)\n    at Object.concatSeries (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:645:23)\n    at Object.exports.runSuite (/Users/alex/Code/karma-nodeunit/lib/nodeunit.js:1727:11)' to contain 'AssertionError: "real" == "this"' (/Users/alex/Code/karma-nodeunit/node_modules/sinon/pkg/sinon.js:1399)
        at global.onerror (/Users/alex/Code/karma-nodeunit/node_modules/mocha/mocha.js:5469:10)
.
Chrome 32.0.1700 (Mac OS X 10.8.5): Executed 5 of 4 (2 FAILED) (0.259 secs / NaN secs)
Warning: Task "karma:adapter" failed. Use --force to continue.

Aborted due to warnings.
```

Worrying things seem to happen:
![ax9v](https://f.cloud.github.com/assets/687961/1567655/a6717c90-50a0-11e3-9f84-73c0df5099b4.jpg)

**Comment by hurrymaplelad** [comment]
Good catch @alexstrat.  Looks like errors are formatted slightly differently in Chrome since it includes a useful stack, and we lost the text of the original assertion.  Update failure formatting to include both the assertion and the stack when both are available.

**Comment by alexstrat** [comment]
Thanks!
